name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'  # Input field to specify the tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create temporary directory
      run: |
        mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: |
        mv temp_dir roadmap-free

    - name: Zip the folder
      run: |
        zip -r roadmap-free-${{ github.event.inputs.tag }}.zip roadmap-free \
        -x "*.git/*" "*.github/*" "roadmap-free/.gitignore" "roadmap-free/.git/*" "roadmap-free/.github/*" \
        "roadmap-free/composer.json" "roadmap-free/composer.lock" \
        "roadmap-free/package.json" "roadmap-free/package-lock.json" \
        "roadmap-free/phpstan.neon" "roadmap-free/phpstan-baseline.neon" \
        "roadmap-free/postcss.config.js" "roadmap-free/tailwind.config.js"



    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: roadmap-free-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write